# Worshop 2.1 Numpy

1. Скачайте этот ноутбук к себе.
2. Заполните пропущенные ячейки, отвечая на заданные вопросы. Там должен быть код! (если не сказано обратное)
3. Сохраните результат в своём гитхаб репозитории.

#### Полезная литература

- http://www.numpy.org/
- https://jakevdp.github.io/PythonDataScienceHandbook/02.00-introduction-to-numpy.html
- https://docs.scipy.org/doc/numpy/user/quickstart.html

1) Импортировать numpy и написать версию

In [1]:
import numpy as np
np.__version__

'1.26.4'

2) Создать нулевой вектор размера 10

In [2]:
print(np.zeros(10))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


3) Создать вектор заполненный 7-ами размера 7

In [4]:
print(np.full(7, 7))

[7 7 7 7 7 7 7]


4) Создать вектор заполненный четными числами от 10 до 100

In [5]:
print(np.arange(10, 101, 2))

[ 10  12  14  16  18  20  22  24  26  28  30  32  34  36  38  40  42  44
  46  48  50  52  54  56  58  60  62  64  66  68  70  72  74  76  78  80
  82  84  86  88  90  92  94  96  98 100]


5) Создать массив случайных чисел и развернуть его задом наперёд

In [6]:
random_array = np.random.randint(0, 10, size=10)
print(random_array)
print(random_array[::-1])

[2 9 1 8 5 0 8 1 1 6]
[6 1 1 8 0 5 8 1 9 2]


6) Создать двумерную матрицу размера 3 на 3, заполненную числами от 0 до 9

In [7]:
print(np.arange(9).reshape(3, 3))

[[0 1 2]
 [3 4 5]
 [6 7 8]]


7) Создать матрицу размера 4 на 4 с единицами на диагонали смещеной на один наверх.

In [8]:

print(np.eye(4, k=1))

[[0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [0. 0. 0. 0.]]


8) Создать матрицу с числами в диапазоне от 1 до 4 по диагонали. В других ячейках матрицы должны быть семерки.

In [9]:
matrix = np.full((4, 4), 7)

np.fill_diagonal(matrix, [1, 2, 3, 4])

print(matrix)

[[1 7 7 7]
 [7 2 7 7]
 [7 7 3 7]
 [7 7 7 4]]


9) Создать матрицу размера 5 на 5 заполненную чилами от 0 до 4 в строках.

In [10]:
print(np.tile(np.arange(5), (5, 1)))

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


10) Создать матрицу случайных чисел размера 10 на 10 и отнять среднее по строкам из каждого элемента строки

In [11]:
matrix = np.random.randint(0, 10, size=(10, 10))
row_means = matrix.mean(axis=1, keepdims=True)
result_matrix = matrix - row_means

print(result_matrix)

[[ 0.2  1.2 -1.8  2.2 -3.8  3.2 -0.8  2.2 -2.8  0.2]
 [-5.2  1.8  3.8 -3.2 -3.2  0.8  2.8  0.8 -0.2  1.8]
 [ 1.   1.  -2.   1.  -3.  -4.   5.   0.   5.  -4. ]
 [-1.  -3.   2.   5.   0.   1.   1.  -2.  -1.  -2. ]
 [ 0.6  1.6  4.6 -2.4 -0.4 -1.4 -2.4  3.6 -3.4 -0.4]
 [ 3.   0.  -3.  -1.   1.  -3.   0.   3.   2.  -2. ]
 [ 3.1  2.1  3.1 -1.9 -3.9 -3.9 -3.9  3.1 -2.9  5.1]
 [ 3.4 -1.6 -4.6  3.4 -3.6 -0.6  2.4  0.4  3.4 -2.6]
 [-0.8 -1.8  4.2 -2.8 -2.8  4.2  3.2 -2.8  1.2 -1.8]
 [ 5.7  0.7 -2.3 -0.3  0.7  2.7 -2.3 -3.3 -1.3 -0.3]]


11) Создать матрицу случайных чисел размера 10 на 10 и отнять медиану по столбцам из каждого элемента столбца  

In [12]:
matrix = np.random.randint(0, 10, size=(10, 10))
column_medians = np.median(matrix, axis=0)
result_matrix = matrix - column_medians

print(result_matrix)

[[ 2.   2.5 -2.5 -3.   5.  -1.   3.   6.  -2.   4.5]
 [-3.   2.5  0.5 -4.   6.   0.  -5.  -2.   6.  -0.5]
 [ 3.  -3.5 -0.5  5.   6.  -2.   1.  -2.  -3.  -1.5]
 [ 0.   2.5 -3.5 -4.  -3.   1.  -1.  -2.   0.  -1.5]
 [ 5.  -0.5  0.5 -3.   1.   3.   2.  -1.   1.  -3.5]
 [-3.  -2.5  0.5  5.  -2.   3.   3.   0.  -3.   3.5]
 [ 0.   0.5 -0.5  5.  -3.   0.  -4.   1.  -1.   0.5]
 [-3.  -3.5  1.5  3.  -2.   0.  -6.   1.   4.   1.5]
 [ 0.  -5.5  0.5  5.   4.   2.   2.   0.   0.  -4.5]
 [-2.   3.5 -1.5 -4.  -1.  -1.  -1.   5.   4.   0.5]]


12) Создать матрицу случайных чисел 5x5. Добавить к ней столбецы максимумов и минимумов по строкам. Получится матрица 5x7.  

In [13]:
matrix = np.random.randint(0, 10, size=(5, 5))

row_maxs = matrix.max(axis=1, keepdims=True)
row_mins = matrix.min(axis=1, keepdims=True)

extended_matrix = np.hstack((matrix, row_maxs, row_mins))

print(extended_matrix)

[[0 2 4 7 0 7 0]
 [1 8 2 6 2 8 1]
 [4 5 3 4 2 5 2]
 [8 7 4 1 7 8 1]
 [1 1 5 6 1 6 1]]


13) Вектор чисел от 1 до 51 преобразовать в вектор нечетных чисел и в вектор четных чисел, поменять их размерности, чтобы получились две матрица. Найти произведение этих матриц. Найти обратную матрицу эётого произведения.  

In [15]:
vector = np.arange(1, 51)

odd_numbers = vector[vector % 2 != 0]
even_numbers = vector[vector % 2 == 0]

odd_matrix = odd_numbers.reshape(5, 5)
even_matrix = even_numbers.reshape(5, 5)

product_matrix = np.dot(odd_matrix, even_matrix)

try:
    inverse_matrix = np.linalg.inv(product_matrix)
    print("Обратная матрица:\n", inverse_matrix)
except np.linalg.LinAlgError:
    print("Обратная матрица не существует (матрица вырождена).")

Обратная матрица:
 [[-1.47679962e+11 -1.83887787e+12  3.34775496e+12 -5.88156445e+11
  -7.73040676e+11]
 [ 1.01212042e+13 -1.18649064e+13 -5.47581546e+11 -3.79493456e+12
   6.08621830e+12]
 [-2.03455911e+13  2.87474748e+13 -5.87413759e+12  6.88821520e+12
  -9.41596130e+12]
 [ 1.09182893e+13 -1.45447188e+13 -0.00000000e+00 -3.90009491e+10
   3.66543041e+12]
 [-5.46222520e+11 -4.98971679e+11  3.07396418e+12 -2.46612325e+12
   4.37353266e+11]]


14) Создать 8x8 матрицу и заполнить её в шахматном порядке нулями и единицами. 

In [16]:
matrix = np.zeros((8, 8), dtype=int)

matrix[::2, 1::2] = 1 
matrix[1::2, ::2] = 1  

print(matrix)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]
